# Generated by Django 6.0.5 on 2026-05-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='hashtags',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='content',
            name='seo_tags',
            field=models.TextField(blank=True),
        ),
    ]
