# Generated by Django 6.0.5 on 2026-05-29 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflow', '0002_content_hashtags_content_seo_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engagement_score', models.FloatField(default=0.0)),
                ('quality_score', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='workflow.content')),
            ],
        ),
    ]
