# Generated by Django 6.0.5 on 2026-05-29 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('workflow', '0002_content_hashtags_content_seo_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViralityPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('label', models.CharField(default='Low', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='virality', to='workflow.content')),
            ],
        ),
    ]
